authors:
  flo:
    display_name: Florian Fendt
    email: flo_fendt@gmx.de
    github: florianfendt
title: Flo's Personal Webpage
url: 'http://florianfendt.github.io'
baseurl:
port: 4444
gems:
  - jekyll-seo-tag


# Meta
name: Florian Fendt
tagline: Developer and Data Scientist
pic: profile.png
email: flo_fendt@gmx.de
phone: 0049 163 4485979
website: florianfendt.github.io
github: florianfendt
instagram: flo_tographer
facebook: Flo Et
site.year: 2017

markdown: kramdown
highlighter: rouge
permalink: /:title/

# Set the Sass partials directory, as we're using @imports
sass:
  sass_dir: _sass
  style: :compressed
